language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - 8.0
  - nightly

matrix:
    allow_failures:
        - php: 7.1
        - php: 8.0
        - php: nightly

sudo: false
sudo: false

install: travis_retry composer install --no-interaction --prefer-dist

script: vendor/bin/phpunit --verbose
